baseURL: "http://ryan890607.github.io/"
languageCode: "en-us"
title: "Ryan (Ting-Wei) Hsu"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Ryan (Ting-Wei) Hsu"
  description: Owow
  # staticPath: ""  # The path to serve the static files from
  favicon: NTU_icon.jpeg

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Ryan (Ting-Wei) Hsu" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
      disableBlog: true
      disableGallery: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Ryan (Ting-Wei) Hsu."
    # subtitle: "I build things for the web"
    content: "A recent computer science graduate with a strong foundation in software engineering."
    image: avatar.jpg
    bottomImage:
      enable: true
      roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: resume.pdf
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fa-solid fa-envelope
          url: "mailto:ryanh4w@gmail.com"
        - icon: fab fa-github
          url: https://github.com/ryan890607
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/ryan-tingwei-hsu

  # About
  about:
    enable: true
    title: "About Me"
    image: avatar.jpg
    content: |-
      I'm a recent computer science graduate, possessing a robust foundation in software engineering. Proficient in C/C++ and Python, I excel in algorithms and data structures. My portfolio includes diverse projects ranging from full-stack development to participation in AI competitions, demonstrating my strong problem-solving skills and innovative approach.

      With outstanding academic performance, I actively seek opportunities for a software engineering position both in the US and Taiwan (No visa support is needed).

    skills:
      enable: true
      title: "Here are a few technologies I've learned in college:"
      items:
        - "C/C++"
        - "Python"
        - "Java"
        - "HTML/CSS/JavaScript"
        - "React"
        - "GraphQL"
        - "Git/GitHub"
        - "Unix/Linux"
        - "Docker"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Software Developer"
        company: "Amazon"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Science in Computer Science and Information Engineering"
        school:
          name: "National Taiwan University"
          url: "https://www.ntu.edu.tw/english/"
        date: "2019 - 2023"
        GPA: "3.98 out of 4.3"
        content: |-
          Coursework
          - Graduate Coursework: Web Programming, Fundamental Object Oriented Programming, Machine Learning, Natural Language Processing, Applied Deep Learning, Digital Image Processing, Introduction to Intelligent Vehicle, Introduction to FinTech.
          - Undergraduate Coursework: Data Structures and Algorithms, Operation system, Computer Networks, Computer Architecture.
          - Special Research: Multimedia Information Retrieval Lab, Image and Vision Lab, Machine Intelligence Lab.

          Extracurricular Activities
          - Participated in winter service camp for 80 students from a rural elementary school in my hometown.
          - Contributed as a member of a baseball team.
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"


  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Interactive Web Service of Food Review Forum
        content: The web development of a food review forum, leveraging React as the primary frontend framework and Node.js as the backend framework.
        image: NTUeat.png
        featured:
          name: Demo
          link: https://www.youtube.com/watch?v=1--dj9WnDDk
        badges:
          - "React"
          - "GraphQL"
          - "Mongodb"
        links:
          - icon: fab fa-github
            url: https://github.com/ryan890607/web-programming-final
      - title: TOMOFUN Sound Classification AI Competition
        content: Developed and deployed over 10 neural network models to classify diverse sounds into 11 distinct categories, incorporating advanced techniques such as data augmentation, time augmentation, and ensemble learning to optimize model performance. 
                 Successfully executed real-time inference on an AWS web service, earning recognition as a top-10 (No. 9) finalist among 300+ participating teams.
        # image: NTUeat.png
        badges:
          - "Python"
          - "Pytorch"
          - "AMAZON EC2"
          - "Flask"
        links:
          - icon: fa-solid fa-ranking-star
            url: https://tbrain.trendmicro.com.tw/Competitions/Details/15
      - title: Side-Scrolling Battle Game
        content: Conceptualized and implemented a 2D side-scrolling game using Java, featuring a software design that prioritizes flexibility and adheres to the open-closed principle.
        image: NTUeat.png
        badges:
          - "Java"
          - "OOP"
        links:
          - icon: fab fa-github
            url: https://github.com/ryan890607/web-programming-final


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: If you have any questions, plz email me, and I'll do my best to respond ASAP!
    email: ryanh4w@gmail.com
    btnName: Click me!
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/ryan890607
      linkedin: https://linkedin.com/in/ryan-tingwei-hsu
      instagram: https://instagram.com/weebaoweewee
      facebook: https://facebook.com/ryan.hsu.332/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>